### ISSUE TITLE
Comment detection

### ISSUE THREAD

**Issue by hmueller01** [Yash-Singh1/cshell-vscode#2]
Could you please add detection of comments (#). Tx.

**Comment by Yash-Singh1** [comment]
This extension just extends the original VSCode `shell` syntax, so it should inherit the comments syntax highlighting. Here is an example:

![Screenshot from 2022-02-12 11-14-02](https://user-images.githubusercontent.com/53054099/153725053-815be634-e888-47ec-9c36-6f85e19acb7f.png)

**Comment by hmueller01** [comment]
Sorry, I am _VERY_ new to VSCode. Just started the day before. Was using ATOM before (without C Shell support).

Ok, I see. I've got an internal language mode called `bash`. Do mean this? It looks like, as using this handles the C Shell files better than selecting cshell language. And with bash selected and C Shell extension enabled e.g. missing `foreach` works. It might help, if you describe this in the README.md ...

Tx for your work!

**Comment by Yash-Singh1** [comment]
> Sorry, I am VERY new to VSCode. Just started the day before. Was using ATOM before (without C Shell support).

No problem. Happy to help.

> Ok, I see. I've got an internal language mode called bash. Do mean this? It looks like, as using this handles the C Shell files better than selecting cshell language. And with bash selected and C Shell extension enabled e.g. missing foreach works. It might help, if you describe this in the README.md ...

Sure, that can probably help people in the future in understanding how this extension is designed.

**Comment by hmueller01** [comment]
This is really strange. On my Mac the language mode shown in the status line is "bash". On my Windows PC is is "shellscript" (same VSCode version), as I would expect it. It's nothing with our extension. But this was the thing which confused me and why I tried to switch it to "cshell" ...

**Comment by Yash-Singh1** [comment]
> This is really strange. On my Mac the language mode shown in the status line is "bash". On my Windows PC is is "shellscript" (same VSCode version), as I would expect it. It's nothing with our extension. But this was the thing which confused me and why I tried to switch it to "cshell" ...

Makes sense, because the grammar itself doesn't have `source.shell` in it. I tried to add a filename pattern to the injected grammar, but it turns out whenever the filename matches, the parent grammar won't be applied to the file, so the same problem will be present, so for now I don't see any apparent solution for this.
